AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 17

Metrics/LineLength:
    Max: 120

Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodLength:
  Max: 20
