AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
  Exclude:
    - loggery-gem.gemspec
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/**/*

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
