sudo: false
language: ruby
rvm:
  - 2.4.2
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
script:  
- bundle exec rubocop
- bundle exec rspec
