sudo: false
language: ruby
rvm:
  - 2.6.4
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
before_install:
  - rvm use @global
script:
- bundle exec rubocop
- bundle exec rspec
